--- Makefile	2020-06-02 01:10:39.399768209 +0300
+++ Makefile.new	2020-06-02 01:08:28.524419647 +0300
@@ -11,9 +11,11 @@
 datarootdir   = ${PREFIX}/share
 datadir       = ${datarootdir}
 
-override CXXFLAGS += --std=gnu++11 -g3
+CXXFLAGS += --std=gnu++11 -g3
 
-all: libprimus_vk.so libnv_vulkan_wrapper.so
+CXXFLAGS += -DNV_DRIVER_PATH=\"libGLX_nvidia.so.0\"
+
+all: libprimus_vk.so libnv_vulkan_wrapper.so primus_vk_diag
 
 libprimus_vk.so: primus_vk.cpp
 	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -I/usr/include/vulkan -shared -fPIC $^ -o $@ -Wl,-soname,libprimus_vk.so.1 -ldl -lpthread $(LDFLAGS)
@@ -30,7 +32,7 @@
 primus_vk.cpp: primus_vk_forwarding.h primus_vk_forwarding_prototypes.h
 
 primus_vk_diag: primus_vk_diag.o
-	$(CXX) -g3 -o $@ $^ -lX11 -lvulkan -ldl $(LDFLAGS)
+	$(CXX) $(CXXFLAGS) -g3 -o $@ $^ -lX11 -lvulkan -ldl $(LDFLAGS)
 
 clean:
 	rm -f libnv_vulkan_wrapper.so libprimus_vk.so
